#! /bin/sh

# defaults
selfupdate=false
git=git
name=""

# read user config
test -f ~/.ysbuilder_conf && source ~/.ysbuilder_conf

# parse command-line options
test "$1" == "-U" && selfupdate=true

# apply config file settings
export BUILDER_SELFUPDATE="$selfupdate"
export BUILDER_NAME="$name"
export PATH

if $selfupdate && ! $git --version >/dev/null; then
  echo
  echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
  echo "Could not locate Git. If it is installed, please specify its path"
  echo "in ~/.ysbuilder_conf, e.g.:"
  echo "  git=/usr/local/bin/git"
  echo
  echo "Alternatively, you can explicitly specify the correct PATH, e.g.:"
  echo "  PATH=/bin:/usr/bin:/usr/local/bin:~/bin"
  echo
  echo "For your reference, the current value of \$PATH is:"
  echo "  $PATH"
  echo
  echo "Automatic updates will be disabled until you resolve this issue."
  echo
  selfupdate=false
fi

cd "$(dirname "$0")"
mydir="$(pwd)"

ruby "$mydir/client/worker.rb" "$@"
if $selfupdate; then
  $git fetch
  $git stash
  $git reset --hard origin/master
fi
exec "$mydir/$(basename "$0")" "$@"
