application: yoursway-builder
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: static/images
- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
- url: .*
  script: main.py
